/**
 * The symbols worth watching, with what they are. Only facts that hold still are kept
 * here — anything that drifts (market cap, price, yield, beta) comes from the data
 * providers when it is needed, so it cannot go stale in this file.
 */

/** The eleven GICS sectors. */
export type GicsSector =
  | 'Communication Services'
  | 'Consumer Discretionary'
  | 'Consumer Staples'
  | 'Energy'
  | 'Financials'
  | 'Health Care'
  | 'Industrials'
  | 'Information Technology'
  | 'Materials'
  | 'Real Estate'
  | 'Utilities';

interface Listing {
  readonly symbol: string;
  readonly name: string;
  /** Your own groupings, free to overlap: 'mega-cap-tech', 'china', 'rates', 'reit', 'defensive'. */
  readonly tags: readonly string[];
  /** Why it's on the list, or what to remember about it. */
  readonly note?: string;
}

export interface WatchedStock extends Listing {
  readonly kind: 'stock';
  readonly sector: GicsSector;
  /** The GICS industry, one level below the sector. */
  readonly industry: string;
  /** Where the business mainly operates, as an ISO 3166 alpha-2 code. */
  readonly country: string;
}

export interface WatchedFund extends Listing {
  readonly kind: 'fund';
  readonly tracks: string;
}

export interface WatchedLeveragedFund extends Listing {
  readonly kind: 'leveraged-fund';
  readonly tracks: string;
  /** The daily multiple of the index return; negative for an inverse fund. */
  readonly leverage: number;
  /** The unleveraged fund on this list that follows the same index, for measuring decay against. */
  readonly proxy: string;
}

/**
 * Named apart from the market data model's `Ticker`, which is a provider's reference
 * record for any symbol; this is a hand-kept description of one we chose to watch.
 */
export type WatchlistEntry = WatchedStock | WatchedFund | WatchedLeveragedFund;

export const WATCHLIST: readonly WatchlistEntry[] = [
  // Indexes
  { symbol: 'SPY', name: 'State Street SPDR S&P 500 ETF Trust', kind: 'fund', tracks: 'S&P 500', tags: ['index'] },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', kind: 'fund', tracks: 'Nasdaq-100', tags: ['index'] },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', kind: 'fund', tracks: 'Russell 2000', tags: ['index', 'small-cap'] },
  {
    symbol: 'TQQQ',
    name: 'ProShares UltraPro QQQ',
    kind: 'leveraged-fund',
    tracks: 'Nasdaq-100',
    leverage: 3,
    proxy: 'QQQ',
    tags: ['index'],
    note: 'Resets daily, so it decays against 3x QQQ in a choppy market.',
  },
  {
    symbol: 'SQQQ',
    name: 'ProShares UltraPro Short QQQ',
    kind: 'leveraged-fund',
    tracks: 'Nasdaq-100',
    leverage: -3,
    proxy: 'QQQ',
    tags: ['index'],
    note: 'Resets daily, so it decays against -3x QQQ in a choppy market.',
  },

  // Bonds and credit
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', kind: 'fund', tracks: 'US Treasuries 20+ years', tags: ['rates', 'bonds'] },
  {
    symbol: 'TMF',
    name: 'Direxion Daily 20+ Year Treasury Bull 3X Shares',
    kind: 'leveraged-fund',
    tracks: 'US Treasuries 20+ years',
    leverage: 3,
    proxy: 'TLT',
    tags: ['rates', 'bonds'],
  },
  {
    symbol: 'HYG',
    name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
    kind: 'fund',
    tracks: 'Markit iBoxx USD Liquid High Yield Index',
    tags: ['bonds', 'credit'],
    note: 'Junk bonds. A credit selloff often shows here before it shows in stocks.',
  },

  // Gold, bitcoin and currencies
  {
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    kind: 'fund',
    tracks: 'Gold bullion',
    tags: ['gold', 'commodity'],
    note: 'Holds physical gold, so unlike USO it tracks the spot price closely.',
  },
  {
    symbol: 'IBIT',
    name: 'iShares Bitcoin Trust ETF',
    kind: 'fund',
    tracks: 'Bitcoin',
    tags: ['crypto'],
    note: 'Holds bitcoin itself. Public only since January 2024.',
  },
  {
    symbol: 'FXY',
    name: 'Invesco CurrencyShares Japanese Yen Trust',
    kind: 'fund',
    tracks: 'Japanese yen against the US dollar',
    tags: ['currency'],
    note: 'Holds yen on deposit, so it rises when the yen strengthens. A read on the yen carry trade, like its sharp unwind in August 2024.',
  },

  // Mega-cap tech
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Technology Hardware, Storage & Peripherals',
    country: 'US',
    tags: ['mega-cap-tech'],
  },
  { symbol: 'MSFT', name: 'Microsoft Corporation', kind: 'stock', sector: 'Information Technology', industry: 'Software', country: 'US', tags: ['mega-cap-tech'] },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    kind: 'stock',
    sector: 'Communication Services',
    industry: 'Interactive Media & Services',
    country: 'US',
    tags: ['mega-cap-tech'],
    note: 'Class A, the voting shares; GOOG is class C.',
  },
  {
    symbol: 'META',
    name: 'Meta Platforms, Inc.',
    kind: 'stock',
    sector: 'Communication Services',
    industry: 'Interactive Media & Services',
    country: 'US',
    tags: ['mega-cap-tech'],
    note: 'Traded as FB until June 2022, so older history may sit under the old symbol.',
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['mega-cap-tech', 'semiconductors', 'chip-designer', 'ai-infrastructure'],
  },
  { symbol: 'TSLA', name: 'Tesla, Inc.', kind: 'stock', sector: 'Consumer Discretionary', industry: 'Automobiles', country: 'US', tags: ['mega-cap-tech'] },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', kind: 'stock', sector: 'Consumer Discretionary', industry: 'Broadline Retail', country: 'US', tags: ['mega-cap-tech'] },

  // Hardware and power
  {
    symbol: 'DELL',
    name: 'Dell Technologies Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Technology Hardware, Storage & Peripherals',
    country: 'US',
    tags: ['ai-infrastructure'],
    note: 'Class C, the only listed class.',
  },
  {
    symbol: 'HPE',
    name: 'Hewlett Packard Enterprise Company',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Technology Hardware, Storage & Peripherals',
    country: 'US',
    tags: ['ai-infrastructure'],
  },
  {
    symbol: 'GEV',
    name: 'GE Vernova Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Electrical Equipment',
    country: 'US',
    tags: ['ai-infrastructure'],
    note: 'Spun off from GE in April 2024, so there is no price history before then.',
  },
  {
    symbol: 'ETN',
    name: 'Eaton Corporation plc',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Electrical Equipment',
    country: 'US',
    tags: ['ai-infrastructure'],
    note: 'Domiciled in Ireland since 2012, but its main operations and most of its revenue are in the US.',
  },
  {
    symbol: 'ANET',
    name: 'Arista Networks, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Communications Equipment',
    country: 'US',
    tags: ['networking', 'ai-infrastructure'],
  },

  // Software
  {
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Software',
    country: 'US',
    tags: ['software', 'cloud', 'ai-infrastructure'],
  },
  { symbol: 'CRM', name: 'Salesforce, Inc.', kind: 'stock', sector: 'Information Technology', industry: 'Software', country: 'US', tags: ['software'] },
  { symbol: 'NOW', name: 'ServiceNow, Inc.', kind: 'stock', sector: 'Information Technology', industry: 'Software', country: 'US', tags: ['software'] },
  {
    symbol: 'SNOW',
    name: 'Snowflake Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'IT Services',
    country: 'US',
    tags: ['software', 'cloud'],
    note: 'Public since its September 2020 IPO.',
  },
  {
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Software',
    country: 'US',
    tags: ['software', 'cybersecurity'],
    note: 'Public since its June 2019 IPO.',
  },
  {
    symbol: 'PANW',
    name: 'Palo Alto Networks, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Software',
    country: 'US',
    tags: ['software', 'cybersecurity'],
  },

  // Semiconductors
  {
    symbol: 'SMH',
    name: 'VanEck Semiconductor ETF',
    kind: 'fund',
    tracks: 'MVIS US Listed Semiconductor 25 Index',
    tags: ['semiconductors'],
    note: 'Only 25 holdings with loose weight caps, so NVDA and TSM dominate it.',
  },
  {
    symbol: 'SOXX',
    name: 'iShares Semiconductor ETF',
    kind: 'fund',
    tracks: 'NYSE Semiconductor Index',
    tags: ['semiconductors'],
    note: 'Caps its largest holdings more tightly than SMH, so it leans less on NVDA.',
  },
  {
    symbol: 'SOXL',
    name: 'Direxion Daily Semiconductor Bull 3X Shares',
    kind: 'leveraged-fund',
    tracks: 'NYSE Semiconductor Index',
    leverage: 3,
    proxy: 'SOXX',
    tags: ['semiconductors'],
    note: 'Resets daily, so it decays against 3x SOXX in a choppy market.',
  },
  {
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['mega-cap-tech', 'semiconductors', 'chip-designer', 'ai-infrastructure'],
    note: 'Also owns VMware, so part of its revenue is software.',
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-designer', 'ai-infrastructure'],
  },
  {
    symbol: 'MRVL',
    name: 'Marvell Technology, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-designer', 'ai-infrastructure'],
  },
  {
    symbol: 'QCOM',
    name: 'QUALCOMM Incorporated',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-designer'],
  },
  {
    symbol: 'ARM',
    name: 'Arm Holdings plc',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'GB',
    tags: ['semiconductors', 'chip-designer'],
    note: 'An ADR, public since its September 2023 IPO. Mostly licenses chip designs, though in March 2026 it announced its first chip of its own, the AGI CPU, with Meta as the first customer. SoftBank owns most of it.',
  },
  {
    symbol: 'INTC',
    name: 'Intel Corporation',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-designer', 'foundry'],
  },
  {
    symbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing Company Limited',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'TW',
    tags: ['semiconductors', 'foundry', 'ai-infrastructure'],
    note: 'An ADR; one share is five Taiwan ordinary shares. Makes the chips NVDA, AAPL and AMD design.',
  },
  {
    symbol: 'MU',
    name: 'Micron Technology, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'memory', 'ai-infrastructure'],
  },
  {
    symbol: 'SKHY',
    name: 'SK hynix Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'KR',
    tags: ['semiconductors', 'memory', 'ai-infrastructure'],
    note: 'An ADR, on Nasdaq only since July 2026; the longer history is in Seoul as 000660. A leading supplier of the high-bandwidth memory on NVDA accelerators.',
  },
  {
    symbol: 'TXN',
    name: 'Texas Instruments Incorporated',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'analog'],
  },
  {
    symbol: 'ASML',
    name: 'ASML Holding N.V.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'NL',
    tags: ['semiconductors', 'chip-equipment'],
    note: 'Listed in New York one-for-one with its Amsterdam shares. The only maker of EUV lithography machines.',
  },
  {
    symbol: 'AMAT',
    name: 'Applied Materials, Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-equipment'],
  },
  {
    symbol: 'LRCX',
    name: 'Lam Research Corporation',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-equipment'],
  },
  {
    symbol: 'KLAC',
    name: 'KLA Corporation',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Semiconductors & Semiconductor Equipment',
    country: 'US',
    tags: ['semiconductors', 'chip-equipment'],
  },

  // Media and telecom
  { symbol: 'NFLX', name: 'Netflix, Inc.', kind: 'stock', sector: 'Communication Services', industry: 'Entertainment', country: 'US', tags: ['media'] },
  { symbol: 'DIS', name: 'The Walt Disney Company', kind: 'stock', sector: 'Communication Services', industry: 'Entertainment', country: 'US', tags: ['media'] },
  {
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    kind: 'stock',
    sector: 'Communication Services',
    industry: 'Diversified Telecommunication Services',
    country: 'US',
    tags: ['telecom', 'defensive'],
  },

  // Internet platforms
  {
    symbol: 'UBER',
    name: 'Uber Technologies, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Ground Transportation',
    country: 'US',
    tags: ['internet-platform', 'gig-economy'],
    note: 'Public since its May 2019 IPO. GICS files it under Industrials, beside the railroads, not under technology.',
  },
  {
    symbol: 'BKNG',
    name: 'Booking Holdings Inc.',
    kind: 'stock',
    sector: 'Consumer Discretionary',
    industry: 'Hotels, Restaurants & Leisure',
    country: 'US',
    tags: ['internet-platform', 'travel'],
  },
  {
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'IT Services',
    country: 'CA',
    tags: ['internet-platform', 'e-commerce', 'software'],
    note: 'Canadian, and listed in both New York and Toronto under the same symbol; not an ADR.',
  },

  // Consumer
  {
    symbol: 'COST',
    name: 'Costco Wholesale Corporation',
    kind: 'stock',
    sector: 'Consumer Staples',
    industry: 'Consumer Staples Distribution & Retail',
    country: 'US',
    tags: ['defensive'],
  },
  {
    symbol: 'WMT',
    name: 'Walmart Inc.',
    kind: 'stock',
    sector: 'Consumer Staples',
    industry: 'Consumer Staples Distribution & Retail',
    country: 'US',
    tags: ['defensive', 'dividend-aristocrat'],
  },
  { symbol: 'KO', name: 'The Coca-Cola Company', kind: 'stock', sector: 'Consumer Staples', industry: 'Beverages', country: 'US', tags: ['defensive', 'dividend-aristocrat'] },
  {
    symbol: 'PG',
    name: 'The Procter & Gamble Company',
    kind: 'stock',
    sector: 'Consumer Staples',
    industry: 'Household Products',
    country: 'US',
    tags: ['defensive', 'dividend-aristocrat'],
  },
  { symbol: 'HD', name: 'The Home Depot, Inc.', kind: 'stock', sector: 'Consumer Discretionary', industry: 'Specialty Retail', country: 'US', tags: ['housing'] },
  {
    symbol: 'NKE',
    name: 'NIKE, Inc.',
    kind: 'stock',
    sector: 'Consumer Discretionary',
    industry: 'Textiles, Apparel & Luxury Goods',
    country: 'US',
    tags: [],
    note: 'Class B, the listed class.',
  },
  {
    symbol: 'MCD',
    name: "McDonald's Corporation",
    kind: 'stock',
    sector: 'Consumer Discretionary',
    industry: 'Hotels, Restaurants & Leisure',
    country: 'US',
    tags: ['dividend-aristocrat'],
  },
  { symbol: 'SBUX', name: 'Starbucks Corporation', kind: 'stock', sector: 'Consumer Discretionary', industry: 'Hotels, Restaurants & Leisure', country: 'US', tags: [] },

  // Real estate
  { symbol: 'SPG', name: 'Simon Property Group, Inc.', kind: 'stock', sector: 'Real Estate', industry: 'Retail REITs', country: 'US', tags: ['reit', 'rates'] },
  {
    symbol: 'O',
    name: 'Realty Income Corporation',
    kind: 'stock',
    sector: 'Real Estate',
    industry: 'Retail REITs',
    country: 'US',
    tags: ['reit', 'rates', 'dividend-aristocrat'],
    note: 'Pays its dividend monthly.',
  },

  // Financials
  {
    symbol: 'BRK.B',
    name: 'Berkshire Hathaway Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Financial Services',
    country: 'US',
    tags: ['conglomerate'],
    note: 'Class B. Providers spell the class suffix differently (BRK.B, BRK-B, BRK/B), so check this one before fetching.',
  },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', kind: 'stock', sector: 'Financials', industry: 'Banks', country: 'US', tags: ['banks', 'money-center'] },
  { symbol: 'BAC', name: 'Bank of America Corporation', kind: 'stock', sector: 'Financials', industry: 'Banks', country: 'US', tags: ['banks', 'money-center'] },
  {
    symbol: 'WFC',
    name: 'Wells Fargo & Company',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Banks',
    country: 'US',
    tags: ['banks', 'money-center'],
    note: 'Under a Federal Reserve cap on its total assets from 2018 until June 2025, so it could not grow its balance sheet over that stretch.',
  },
  { symbol: 'C', name: 'Citigroup Inc.', kind: 'stock', sector: 'Financials', industry: 'Banks', country: 'US', tags: ['banks', 'money-center'] },
  {
    symbol: 'GS',
    name: 'The Goldman Sachs Group, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Capital Markets',
    country: 'US',
    tags: ['banks', 'investment-bank'],
  },
  { symbol: 'MS', name: 'Morgan Stanley', kind: 'stock', sector: 'Financials', industry: 'Capital Markets', country: 'US', tags: ['banks', 'investment-bank'] },
  { symbol: 'USB', name: 'U.S. Bancorp', kind: 'stock', sector: 'Financials', industry: 'Banks', country: 'US', tags: ['banks', 'regional-bank'] },
  {
    symbol: 'PNC',
    name: 'The PNC Financial Services Group, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Banks',
    country: 'US',
    tags: ['banks', 'regional-bank'],
  },
  {
    symbol: 'KRE',
    name: 'State Street SPDR S&P Regional Banking ETF',
    kind: 'fund',
    tracks: 'S&P Regional Banks Select Industry',
    tags: ['banks', 'regional-bank'],
    note: 'Close to equal-weighted, so smaller regionals count as much as the large ones. The one to watch in a regional bank scare like March 2023.',
  },

  // Asset managers, brokers and exchanges
  { symbol: 'BLK', name: 'BlackRock, Inc.', kind: 'stock', sector: 'Financials', industry: 'Capital Markets', country: 'US', tags: ['asset-manager'] },
  {
    symbol: 'SCHW',
    name: 'The Charles Schwab Corporation',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Capital Markets',
    country: 'US',
    tags: ['brokerage'],
    note: 'Earns much of its revenue on client cash, which is why it fell with the regional banks in March 2023.',
  },
  { symbol: 'CME', name: 'CME Group Inc.', kind: 'stock', sector: 'Financials', industry: 'Capital Markets', country: 'US', tags: ['exchange'] },
  {
    symbol: 'ICE',
    name: 'Intercontinental Exchange, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Capital Markets',
    country: 'US',
    tags: ['exchange'],
    note: 'Owns the New York Stock Exchange.',
  },
  {
    symbol: 'SPGI',
    name: 'S&P Global Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Capital Markets',
    country: 'US',
    tags: ['financial-data', 'dividend-aristocrat'],
    note: 'Owns the S&P indexes and the S&P credit ratings business.',
  },

  // Fintech and payments
  { symbol: 'V', name: 'Visa Inc.', kind: 'stock', sector: 'Financials', industry: 'Financial Services', country: 'US', tags: ['payments', 'card-network'] },
  { symbol: 'MA', name: 'Mastercard Incorporated', kind: 'stock', sector: 'Financials', industry: 'Financial Services', country: 'US', tags: ['payments', 'card-network'] },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.', kind: 'stock', sector: 'Financials', industry: 'Financial Services', country: 'US', tags: ['fintech', 'payments'] },
  {
    symbol: 'XYZ',
    name: 'Block, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Financial Services',
    country: 'US',
    tags: ['fintech', 'payments'],
    note: 'Traded as SQ until January 2025, so older history may sit under the old symbol.',
  },
  {
    symbol: 'AFRM',
    name: 'Affirm Holdings, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Financial Services',
    country: 'US',
    tags: ['fintech', 'payments', 'lending'],
    note: 'Public since its January 2021 IPO.',
  },
  {
    symbol: 'SOFI',
    name: 'SoFi Technologies, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Consumer Finance',
    country: 'US',
    tags: ['fintech', 'lending'],
    note: 'Public since merging with a SPAC in June 2021.',
  },
  {
    symbol: 'HOOD',
    name: 'Robinhood Markets, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Capital Markets',
    country: 'US',
    tags: ['fintech', 'brokerage'],
    note: 'Public since its July 2021 IPO.',
  },
  {
    symbol: 'COIN',
    name: 'Coinbase Global, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Capital Markets',
    country: 'US',
    tags: ['fintech', 'crypto'],
    note: 'Public since its April 2021 direct listing. Moves with bitcoin more than with other fintech stocks.',
  },
  {
    symbol: 'CRCL',
    name: 'Circle Internet Group, Inc.',
    kind: 'stock',
    sector: 'Financials',
    industry: 'Financial Services',
    country: 'US',
    tags: ['fintech', 'crypto'],
    note: 'Public since its June 2025 IPO. Most of its revenue is interest on the reserves backing USDC, so lower short-term rates cut straight into it.',
  },

  // Health care
  {
    symbol: 'XLV',
    name: 'State Street Health Care Select Sector SPDR ETF',
    kind: 'fund',
    tracks: 'Health Care Select Sector Index',
    tags: ['health-care'],
    note: 'Weighted by market cap, so the largest drugmakers and insurers dominate it.',
  },
  {
    symbol: 'XBI',
    name: 'State Street SPDR S&P Biotech ETF',
    kind: 'fund',
    tracks: 'S&P Biotechnology Select Industry',
    tags: ['health-care', 'biotech'],
    note: 'Close to equal-weighted, so small drug developers count as much as the large ones. A risk-appetite gauge more than a health care one.',
  },
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Pharmaceuticals',
    country: 'US',
    tags: ['health-care', 'pharma', 'defensive', 'dividend-aristocrat'],
    note: 'Separated its consumer health business as Kenvue (KVUE) in 2023; prices before then include it.',
  },
  {
    symbol: 'LLY',
    name: 'Eli Lilly and Company',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Pharmaceuticals',
    country: 'US',
    tags: ['health-care', 'pharma', 'glp-1'],
  },
  {
    symbol: 'NVO',
    name: 'Novo Nordisk A/S',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Pharmaceuticals',
    country: 'DK',
    tags: ['health-care', 'pharma', 'glp-1'],
    note: 'An ADR; one share is one Copenhagen B share.',
  },
  { symbol: 'MRK', name: 'Merck & Co., Inc.', kind: 'stock', sector: 'Health Care', industry: 'Pharmaceuticals', country: 'US', tags: ['health-care', 'pharma'] },
  { symbol: 'PFE', name: 'Pfizer Inc.', kind: 'stock', sector: 'Health Care', industry: 'Pharmaceuticals', country: 'US', tags: ['health-care', 'pharma'] },
  {
    symbol: 'ABBV',
    name: 'AbbVie Inc.',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Biotechnology',
    country: 'US',
    tags: ['health-care', 'pharma', 'dividend-aristocrat'],
    note: 'GICS files it under Biotechnology, but it runs as a large drugmaker, hence the pharma tag.',
  },
  {
    symbol: 'UNH',
    name: 'UnitedHealth Group Incorporated',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Health Care Providers & Services',
    country: 'US',
    tags: ['health-care', 'managed-care'],
  },
  {
    symbol: 'CVS',
    name: 'CVS Health Corporation',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Health Care Providers & Services',
    country: 'US',
    tags: ['health-care', 'managed-care'],
    note: 'A pharmacy chain, but it owns Aetna, so it trades partly as a health insurer.',
  },
  {
    symbol: 'ISRG',
    name: 'Intuitive Surgical, Inc.',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Health Care Equipment & Supplies',
    country: 'US',
    tags: ['health-care', 'medtech'],
  },
  {
    symbol: 'BSX',
    name: 'Boston Scientific Corporation',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Health Care Equipment & Supplies',
    country: 'US',
    tags: ['health-care', 'medtech'],
  },
  {
    symbol: 'TMO',
    name: 'Thermo Fisher Scientific Inc.',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Life Sciences Tools & Services',
    country: 'US',
    tags: ['health-care', 'life-sciences'],
  },
  {
    symbol: 'DHR',
    name: 'Danaher Corporation',
    kind: 'stock',
    sector: 'Health Care',
    industry: 'Life Sciences Tools & Services',
    country: 'US',
    tags: ['health-care', 'life-sciences'],
    note: 'Spun off Veralto in September 2023; prices before then include it.',
  },

  // Energy
  {
    symbol: 'XLE',
    name: 'State Street Energy Select Sector SPDR ETF',
    kind: 'fund',
    tracks: 'Energy Select Sector Index',
    tags: ['energy'],
    note: 'Weighted by market cap, so XOM and CVX make up a large share of it.',
  },
  {
    symbol: 'USO',
    name: 'United States Oil Fund',
    kind: 'fund',
    tracks: 'WTI crude oil futures',
    tags: ['energy', 'commodity'],
    note: 'Holds oil futures rather than oil companies, mostly the nearest month with some later ones, and falls behind the spot price whenever it rolls into a higher-priced contract.',
  },
  {
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    kind: 'stock',
    sector: 'Energy',
    industry: 'Oil, Gas & Consumable Fuels',
    country: 'US',
    tags: ['energy', 'oil-major', 'dividend-aristocrat'],
  },
  {
    symbol: 'CVX',
    name: 'Chevron Corporation',
    kind: 'stock',
    sector: 'Energy',
    industry: 'Oil, Gas & Consumable Fuels',
    country: 'US',
    tags: ['energy', 'oil-major', 'dividend-aristocrat'],
  },
  {
    symbol: 'SHEL',
    name: 'Shell plc',
    kind: 'stock',
    sector: 'Energy',
    industry: 'Oil, Gas & Consumable Fuels',
    country: 'GB',
    tags: ['energy', 'oil-major'],
    note: 'An ADR; one share is two London ordinary shares. Traded as RDS.A and RDS.B until the two share classes merged in January 2022.',
  },
  {
    symbol: 'COP',
    name: 'ConocoPhillips',
    kind: 'stock',
    sector: 'Energy',
    industry: 'Oil, Gas & Consumable Fuels',
    country: 'US',
    tags: ['energy', 'exploration-production'],
  },
  {
    symbol: 'OXY',
    name: 'Occidental Petroleum Corporation',
    kind: 'stock',
    sector: 'Energy',
    industry: 'Oil, Gas & Consumable Fuels',
    country: 'US',
    tags: ['energy', 'exploration-production'],
  },
  {
    symbol: 'MPC',
    name: 'Marathon Petroleum Corporation',
    kind: 'stock',
    sector: 'Energy',
    industry: 'Oil, Gas & Consumable Fuels',
    country: 'US',
    tags: ['energy', 'refiner'],
    note: 'A refiner, so it earns on the gap between crude and fuel prices rather than on the crude price itself.',
  },

  // Utilities
  {
    symbol: 'XLU',
    name: 'State Street Utilities Select Sector SPDR ETF',
    kind: 'fund',
    tracks: 'Utilities Select Sector Index',
    tags: ['utilities', 'rates', 'defensive'],
  },
  {
    symbol: 'NEE',
    name: 'NextEra Energy, Inc.',
    kind: 'stock',
    sector: 'Utilities',
    industry: 'Electric Utilities',
    country: 'US',
    tags: ['utilities', 'rates', 'dividend-aristocrat'],
  },
  {
    symbol: 'VST',
    name: 'Vistra Corp.',
    kind: 'stock',
    sector: 'Utilities',
    industry: 'Independent Power and Renewable Electricity Producers',
    country: 'US',
    tags: ['utilities', 'ai-infrastructure'],
    note: 'Sells power at market prices rather than earning a regulated return, so it trades on power prices and data center demand, not like a utility.',
  },
  {
    symbol: 'CEG',
    name: 'Constellation Energy Corporation',
    kind: 'stock',
    sector: 'Utilities',
    industry: 'Electric Utilities',
    country: 'US',
    tags: ['utilities', 'nuclear', 'ai-infrastructure'],
    note: 'The largest US nuclear power operator. Spun off from Exelon in February 2022, so there is no price history before then.',
  },

  // Materials
  {
    symbol: 'LIN',
    name: 'Linde plc',
    kind: 'stock',
    sector: 'Materials',
    industry: 'Chemicals',
    country: 'US',
    tags: ['materials', 'defensive', 'dividend-aristocrat'],
    note: 'Incorporated in Ireland and run from the UK, but the Americas are its largest market and it lists only in New York.',
  },
  {
    symbol: 'FCX',
    name: 'Freeport-McMoRan Inc.',
    kind: 'stock',
    sector: 'Materials',
    industry: 'Metals & Mining',
    country: 'US',
    tags: ['materials', 'copper'],
    note: 'Trades mostly on the copper price; its largest mine, Grasberg, is in Indonesia.',
  },
  {
    symbol: 'NEM',
    name: 'Newmont Corporation',
    kind: 'stock',
    sector: 'Materials',
    industry: 'Metals & Mining',
    country: 'US',
    tags: ['materials', 'gold'],
    note: 'A gold miner, so it moves more than GLD in both directions: its costs are roughly fixed, and the gold price is not.',
  },

  // Airlines
  {
    symbol: 'DAL',
    name: 'Delta Air Lines, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Passenger Airlines',
    country: 'US',
    tags: ['airlines', 'legacy-carrier'],
  },
  {
    symbol: 'UAL',
    name: 'United Airlines Holdings, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Passenger Airlines',
    country: 'US',
    tags: ['airlines', 'legacy-carrier'],
  },
  {
    symbol: 'AAL',
    name: 'American Airlines Group Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Passenger Airlines',
    country: 'US',
    tags: ['airlines', 'legacy-carrier'],
    note: 'Formed when AMR left bankruptcy and merged with US Airways; trades as AAL only since December 2013.',
  },
  {
    symbol: 'LUV',
    name: 'Southwest Airlines Co.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Passenger Airlines',
    country: 'US',
    tags: ['airlines', 'low-cost'],
  },
  {
    symbol: 'JBLU',
    name: 'JetBlue Airways Corporation',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Passenger Airlines',
    country: 'US',
    tags: ['airlines', 'low-cost'],
  },
  {
    symbol: 'ALK',
    name: 'Alaska Air Group, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Passenger Airlines',
    country: 'US',
    tags: ['airlines'],
    note: 'Bought Hawaiian Airlines in September 2024.',
  },
  {
    symbol: 'JETS',
    name: 'U.S. Global Jets ETF',
    kind: 'fund',
    tracks: 'U.S. Global Jets Index',
    tags: ['airlines'],
    note: 'Mostly the big US carriers, but also holds foreign airlines, airports and aircraft makers.',
  },

  // Industrials
  { symbol: 'CAT', name: 'Caterpillar Inc.', kind: 'stock', sector: 'Industrials', industry: 'Machinery', country: 'US', tags: ['cyclical', 'dividend-aristocrat'] },
  {
    symbol: 'BA',
    name: 'The Boeing Company',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['aerospace', 'defense'],
    note: 'Mostly commercial jets, but its defense and space arm is one of the largest Pentagon contractors.',
  },
  { symbol: 'UNP', name: 'Union Pacific Corporation', kind: 'stock', sector: 'Industrials', industry: 'Ground Transportation', country: 'US', tags: ['freight', 'cyclical'] },
  {
    symbol: 'UPS',
    name: 'United Parcel Service, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Air Freight & Logistics',
    country: 'US',
    tags: ['freight', 'cyclical'],
  },

  // Defense
  {
    symbol: 'ITA',
    name: 'iShares U.S. Aerospace & Defense ETF',
    kind: 'fund',
    tracks: 'Dow Jones U.S. Select Aerospace & Defense Index',
    tags: ['defense', 'aerospace'],
    note: 'Also holds commercial aerospace like BA, so it is not a pure defense fund.',
  },
  {
    symbol: 'LMT',
    name: 'Lockheed Martin Corporation',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'defense-prime', 'aerospace'],
  },
  {
    symbol: 'RTX',
    name: 'RTX Corporation',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'defense-prime', 'aerospace'],
    note: 'Formed when United Technologies merged with Raytheon in April 2020; history before then is under UTX. Also makes commercial jet engines.',
  },
  {
    symbol: 'NOC',
    name: 'Northrop Grumman Corporation',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'defense-prime'],
  },
  {
    symbol: 'GD',
    name: 'General Dynamics Corporation',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'defense-prime', 'aerospace', 'dividend-aristocrat'],
    note: 'Builds nuclear submarines, and also Gulfstream business jets.',
  },
  {
    symbol: 'LHX',
    name: 'L3Harris Technologies, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'defense-prime'],
    note: 'Formed when Harris merged with L3 in 2019; history before then is under HRS.',
  },
  {
    symbol: 'HII',
    name: 'Huntington Ingalls Industries, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense'],
    note: 'The largest US Navy shipbuilder.',
  },
  {
    symbol: 'AVAV',
    name: 'AeroVironment, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'drones'],
  },
  {
    symbol: 'KTOS',
    name: 'Kratos Defense & Security Solutions, Inc.',
    kind: 'stock',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    country: 'US',
    tags: ['defense', 'drones'],
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies Inc.',
    kind: 'stock',
    sector: 'Information Technology',
    industry: 'Software',
    country: 'US',
    tags: ['defense', 'software'],
    note: 'Public since its September 2020 direct listing. Sells data software to governments and companies alike, so it is only partly a defense stock.',
  },

  // China and emerging markets
  {
    symbol: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    kind: 'fund',
    tracks: 'MSCI Emerging Markets',
    tags: ['emerging-markets'],
    note: 'China, Taiwan and India make up most of it.',
  },
  {
    symbol: 'BABA',
    name: 'Alibaba Group Holding Limited',
    kind: 'stock',
    sector: 'Consumer Discretionary',
    industry: 'Broadline Retail',
    country: 'CN',
    tags: ['china'],
    note: 'An ADR; one share is eight Hong Kong ordinary shares.',
  },
  {
    symbol: 'PDD',
    name: 'PDD Holdings Inc.',
    kind: 'stock',
    sector: 'Consumer Discretionary',
    industry: 'Broadline Retail',
    country: 'CN',
    tags: ['china'],
    note: 'An ADR. Headquartered in Dublin since 2023, but Pinduoduo and Temu run on a Chinese business.',
  },
  {
    symbol: 'JD',
    name: 'JD.com, Inc.',
    kind: 'stock',
    sector: 'Consumer Discretionary',
    industry: 'Broadline Retail',
    country: 'CN',
    tags: ['china'],
    note: 'An ADR; one share is two Hong Kong ordinary shares.',
  },
  { symbol: 'FXI', name: 'iShares China Large-Cap ETF', kind: 'fund', tracks: 'FTSE China 50', tags: ['china'] },
];
